# Use the official Ubuntu 18.04 image
FROM ubuntu:18.04

# Install Redis
RUN apt-get update && \
    apt-get install -y redis-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install the Redis Python client
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install redis && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Modify the Redis configuration
RUN sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf

# Expose Redis port
EXPOSE 6379

# Start Redis server
CMD service redis-server start && tail -f /var/log/redis/redis-server.log
